/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pennyboatpackage;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Point2D;

/**
 * A display panel that displays a boat and box that can change shape
 * @author Logan Pfeifer
 * @version 1.0
 * Created 22 April 2014
 */
public class DrawingBoard extends javax.swing.JPanel {
    
    
    Point2D.Double origin     = new Point2D.Double(425, 288);   //the origin point of both the box and the boat
    Point2D.Double waterLevel = new Point2D.Double(0, 288);     //the water level
    int boatLength = 418;   //initial length of the boat    
    int boxLength  = 300
            ;   //initial lenght of the box
    int waterDisplacement = 18; //how much the water is moved
    
    
    
    
    /**
     * Creates new form DrawingBoard
     */
    public DrawingBoard() {
        initComponents();
        this.setBackground(Color.WHITE);
        
    }
    
    /**
     * Changes the height in the frame of the mass
     * @param newHeight the new height (starting height is 288)
     * @return true
     */
    public boolean setMassHeight(int newHeight) {
        origin.setLocation(origin.x, newHeight);
        repaint();
        return true;
    }
    
    /**
     * sets the length of the boat
     * @param length new length of the boat
     * @return true if the length is valid, false if not
     */
    public boolean setBoatLength(int length){
        if(length <= 0)
            return false;
        boatLength = length;
        repaint();
        return true;
    }
    
    /**
     * sets the length of the box
     * @param length new length of the box
     * @return true if the length is valid, false if not
     */
    public boolean setboxLength(int length) {
        if (length <= 0)
            return false;
        boxLength = length;
        repaint();
        return true;
    }
    
    @Override
    public void paintComponent(Graphics g){
        Graphics2D g2 = (Graphics2D) g; //recovers Graphics2D for use
        super.paintComponent(g);        //paints the original component
        
        //sets the color to blue
        g2.setColor(new Color( 0, 102, 255));
        
        //makes a blue rectangle (water)
        
        g2.fillRect((int) waterLevel.x, (int) waterLevel.y + waterDisplacement, 425*23, 288);
        
        //sets the height of the boat in the water respectively to the size of
        //the mass and length of the ship
        if ( boxLength+75 >= boatLength * 1.0) 
            origin.y = 400;
        else if ( boatLength - boxLength <= 75)  origin.y = 294;
        else if ( boatLength - boxLength <= 88)  origin.y = 292;
        else if ( boatLength - boxLength <= 100) origin.y = 290;
        else if ( boatLength - boxLength <= 113) origin.y = 287;
        else if ( boatLength - boxLength <= 125) origin.y = 285;
        else if ( boatLength - boxLength <= 138) origin.y = 282;
        else if ( boatLength - boxLength <= 150) origin.y = 280;
        else if ( boatLength - boxLength <= 153) origin.y = 277;
        else if ( boatLength - boxLength <= 175) origin.y = 275;
        else if ( boatLength - boxLength <= 188) origin.y = 272;
        else if ( boatLength - boxLength <= 200) origin.y = 270;
        else if ( boatLength - boxLength <= 213) origin.y = 268;
        else if ( boatLength - boxLength <= 225) origin.y = 266;
            
        //draws the boat and the box
        Boat boat = new Boat(origin, boatLength);
        Box  box  = new Box (origin, boxLength);
        boat.drawBoat(g);
        box.drawBox(g);
        
        
        
            
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();

        jToggleButton1.setText("jToggleButton1");

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
